# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      data:
        required: true
        type: string
      data2:
        required: false
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  print-inputs:
    name: Print Inputs
    runs-on: ubuntu-latest
    steps:
      - name: Print data
        run: echo "Data- ${{ github.event.inputs.data }}"
      - name: Print data2
        run: echo "Data2- ${{ secrets.GITHUB_TOKEN }}"
        
  modify-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Modify .txt file
      run: |
        echo "Appending new line to the file" >> //content.txt

    - name: Commit changes
      run: |
        git config --global user.name 'bonduSeo'
        git config --global user.email 'bondu.seo@gmail.com'
        git add ./content.txt
        git commit -m "Update .txt file from GitHub Actions"
    
    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push
