# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello, GitHub Actions!'
  pwd-ls:
    name: PWD & LS
    runs-on: ubuntu-latest
    steps:
      - name: Print working directory
        run: pwd
      - name: List files
        run: ls -al

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # 수동으로 workflow를 trigger시켰을 때 `inputs`값이 잘 들어오는지 확인해줍니다.
      - name: Echo variables
        run: |
          # 이전 글에서 배포할 브랜치(ex. deploy/twn/qa/test)를 push하고 파싱하여
          # region(twn)과 env(qa)값을 가져왔었는데요, 이젠 그럴 필요가 없습니다.
          # `workflow_dispatch`를 이용하면 `github.event.inputs`이라는 키워드로 원하는 값을 받을 수 있습니다.
          # region, env는 어떻게 받냐구요? 글을 쭉 읽어주세요!
          echo "data: ${{ github.event.inputs.data }}"
          # echo "region: ${{ github.event.inputs.region }}"
